name: Maven build

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master
  schedule:
  - cron: 0 2 * * 1-5

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
        jdk_version: [1.8, 11]

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK ${{ matrix.jdk_version }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.jdk_version }}
    - name: Build with Maven
      run: mvn clean install
